#!/bin/sh
# build Defs.hs and Names.hs into the source tree with the given gen-xhb-keysyms command

if [ -z "$1" ]; then
    echo "expected gen-xhb-keysyms command"
    exit 1
fi

outdir=$(dirname $0)/Graphics/XHB/KeySym
mkdir -p $outdir
curl 'https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h' | $1 $outdir/Defs.hs $outdir/Names/Internal.hs
curl 'https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h' | $(dirname $0)/validate $outdir/Defs.hs
